kind: Deployment
apiVersion: apps/v1
metadata:
  name: model1-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model1
  template:
    metadata:
      labels:
        app: model1
    spec:
      containers:
      - name: model1
        image: core.harbor.domain/library/model1
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
