apiVersion: v1
kind: Service
metadata:
  name: model1-service
  labels:
    app: model1
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: model1
