apiVersion: v1
kind: Service
metadata:
  name: modeltest12v1-1-service
  labels:
    app: modeltest12
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: modeltest12
