apiVersion: v1
kind: Service
metadata:
  name: modeltest45-service
  labels:
    app: modeltest45
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: modeltest45
